# Generated by Django 2.2.28 on 2024-03-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connected', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
