# Generated by Django 2.2.28 on 2024-03-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connected', '0005_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
