# Generated by Django 2.2.28 on 2024-03-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connected', '0006_auto_20240321_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends_plus', to='connected.UserProfile'),
        ),
    ]
